package com.blibli.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class UserInfo {
    /**
     * Database Column Remarks:
     *   用户ID（自增主键）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   用户邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   用户密码（建议加密存储）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   性别：0=女；1=男；2=未知
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbg.generated
     */
    private Byte sex;

    /**
     * Database Column Remarks:
     *   用户生日（改用DATE类型，更规范）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   就读/毕业学校
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     * Database Column Remarks:
     *   个人简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.person_introduction
     *
     * @mbg.generated
     */
    private String personIntroduction;

    /**
     * Database Column Remarks:
     *   加入时间（默认当前时间）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.join_time
     *
     * @mbg.generated
     */
    private Date joinTime;

    /**
     * Database Column Remarks:
     *   最后登录时间（改用DATETIME类型）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     * Database Column Remarks:
     *   最后登录IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_ip
     *
     * @mbg.generated
     */
    private String lastLoginIp;

    /**
     * Database Column Remarks:
     *   账号状态：0=禁用；1=正常
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   个人空间公告
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.notice_info
     *
     * @mbg.generated
     */
    private String noticeInfo;

    /**
     * Database Column Remarks:
     *   总硬币数量（整数默认0）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.total_coin_count
     *
     * @mbg.generated
     */
    private Integer totalCoinCount;

    /**
     * Database Column Remarks:
     *   当前硬币数量（整数默认0）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.current_coin_count
     *
     * @mbg.generated
     */
    private Integer currentCoinCount;

    /**
     * Database Column Remarks:
     *   界面主题：0=默认；1=深色等（补充默认值）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.theme
     *
     * @mbg.generated
     */
    private Byte theme;

    /**
     * Database Column Remarks:
     *   用户账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_account
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nick_name
     *
     * @return the value of user_info.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nick_name
     *
     * @param nickName the value for user_info.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbg.generated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbg.generated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.school
     *
     * @return the value of user_info.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.school
     *
     * @param school the value for user_info.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.person_introduction
     *
     * @return the value of user_info.person_introduction
     *
     * @mbg.generated
     */
    public String getPersonIntroduction() {
        return personIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.person_introduction
     *
     * @param personIntroduction the value for user_info.person_introduction
     *
     * @mbg.generated
     */
    public void setPersonIntroduction(String personIntroduction) {
        this.personIntroduction = personIntroduction == null ? null : personIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.join_time
     *
     * @return the value of user_info.join_time
     *
     * @mbg.generated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.join_time
     *
     * @param joinTime the value for user_info.join_time
     *
     * @mbg.generated
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_login_time
     *
     * @return the value of user_info.last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_login_time
     *
     * @param lastLoginTime the value for user_info.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_login_ip
     *
     * @return the value of user_info.last_login_ip
     *
     * @mbg.generated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_login_ip
     *
     * @param lastLoginIp the value for user_info.last_login_ip
     *
     * @mbg.generated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.notice_info
     *
     * @return the value of user_info.notice_info
     *
     * @mbg.generated
     */
    public String getNoticeInfo() {
        return noticeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.notice_info
     *
     * @param noticeInfo the value for user_info.notice_info
     *
     * @mbg.generated
     */
    public void setNoticeInfo(String noticeInfo) {
        this.noticeInfo = noticeInfo == null ? null : noticeInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.total_coin_count
     *
     * @return the value of user_info.total_coin_count
     *
     * @mbg.generated
     */
    public Integer getTotalCoinCount() {
        return totalCoinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.total_coin_count
     *
     * @param totalCoinCount the value for user_info.total_coin_count
     *
     * @mbg.generated
     */
    public void setTotalCoinCount(Integer totalCoinCount) {
        this.totalCoinCount = totalCoinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.current_coin_count
     *
     * @return the value of user_info.current_coin_count
     *
     * @mbg.generated
     */
    public Integer getCurrentCoinCount() {
        return currentCoinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.current_coin_count
     *
     * @param currentCoinCount the value for user_info.current_coin_count
     *
     * @mbg.generated
     */
    public void setCurrentCoinCount(Integer currentCoinCount) {
        this.currentCoinCount = currentCoinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.theme
     *
     * @return the value of user_info.theme
     *
     * @mbg.generated
     */
    public Byte getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.theme
     *
     * @param theme the value for user_info.theme
     *
     * @mbg.generated
     */
    public void setTheme(Byte theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_account
     *
     * @return the value of user_info.user_account
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_account
     *
     * @param userAccount the value for user_info.user_account
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", nickName=").append(nickName);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", school=").append(school);
        sb.append(", personIntroduction=").append(personIntroduction);
        sb.append(", joinTime=").append(joinTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", status=").append(status);
        sb.append(", noticeInfo=").append(noticeInfo);
        sb.append(", totalCoinCount=").append(totalCoinCount);
        sb.append(", currentCoinCount=").append(currentCoinCount);
        sb.append(", theme=").append(theme);
        sb.append(", userAccount=").append(userAccount);
        sb.append("]");
        return sb.toString();
    }
}